baseURL = "https://rashmibanthia.github.io/"
languageCode = "en-us"
title = ""
publishDir = "docs"
theme = "minimal"


[params]
    author =  "Rashmi Banthia" 
    description = ""
    githubUsername = "rashmibanthia"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = [] #["go", "haskell", "kotlin", "scala", "swift"]


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

#[[menu.main]]
#    url = "/about/"
#    name = "About"
#    weight = 2

#[[menu.main]]
#    url = "/post/"
#    name = "Posts"
#    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "fas fa-envelope"
#    weight = 1


[[menu.icon]]
    url = "https://www.kaggle.com/rashmibanthia"
    name = "fab fa-kaggle"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rashmibanthia/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rashmigb/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/rashmibanthia/"
    name = "fab fa-linkedin"
    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "fab fa-stack-overflow"
#    weight = 5


